import { describe, expect, it } from 'vitest'
import { InMemoryWebhookAdmissionStore, WebhookAdmissionError, admitIncomingWebhook, bodyFingerprint, signIncomingWebhook, signingMaterial, validateFreshness, verifyIncomingSignature } from './admission.js'
import type { AdmissionInput } from './admission.js'

const base = (): AdmissionInput => ({ tenantId: 'tenant-a', eventId: 'evt-1', timestamp: 1000, rawBody: '{"amount":10}', signature: '', secret: 'secret-a' })
const signed = (): AdmissionInput => { const input = base(); input.signature = signIncomingWebhook(input, input.secret); return input }

describe('webhook admission security boundary', () => {
  it('signs the exact raw payload', () => { const input = base(); const signature = signIncomingWebhook(input, input.secret); expect(signature).toMatch(/^[a-f0-9]{64}$/); expect(signIncomingWebhook({ ...input, rawBody: '{"amount":11}' }, input.secret)).not.toBe(signature) })
  it('binds tenant and event identity into the signature', () => { const input = signed(); expect(() => verifyIncomingSignature({ ...input, tenantId: 'tenant-b' })).toThrow('invalid'); expect(() => verifyIncomingSignature({ ...input, eventId: 'evt-2' })).toThrow('invalid') })
  it('accepts the v1= transport prefix', () => { const input = signed(); expect(() => verifyIncomingSignature({ ...input, signature: `v1=${input.signature}` })).not.toThrow() })
  it('rejects altered raw bytes', () => { const input = signed(); expect(() => verifyIncomingSignature({ ...input, rawBody: '{"amount": 10}' })).toThrow(WebhookAdmissionError) })
  it('rejects altered secret', () => { const input = signed(); expect(() => verifyIncomingSignature({ ...input, secret: 'secret-b' })).toThrow('invalid') })
  it('rejects malformed signature text', () => { expect(() => verifyIncomingSignature({ ...base(), signature: 'not-hex' })).toThrow('invalid') })
  it('rejects a short signature without timing comparison', () => { const input = signed(); expect(() => verifyIncomingSignature({ ...input, signature: input.signature.slice(2) })).toThrow('invalid') })
  it('rejects missing tenant', () => { const input = signed(); expect(() => verifyIncomingSignature({ ...input, tenantId: '' })).toThrow('identity') })
  it('rejects missing event id', () => { const input = signed(); expect(() => verifyIncomingSignature({ ...input, eventId: '' })).toThrow('identity') })
  it('rejects invalid timestamps', () => { const input = signed(); expect(() => verifyIncomingSignature({ ...input, timestamp: 0 })).toThrow('timestamp') })
  it('requires a secret for signing', () => { expect(() => signIncomingWebhook(base(), '')).toThrow('secret') })
  it('keeps Buffer and UTF-8 string bodies equivalent', () => { const input = signed(); const bufferInput = { ...input, rawBody: Buffer.from(input.rawBody as string) }; expect(() => verifyIncomingSignature(bufferInput)).not.toThrow() })
  it('rejects stale timestamps', () => expect(() => validateFreshness(100, 500)).toThrow('outside'))
  it('rejects future timestamps outside tolerance', () => expect(() => validateFreshness(900, 100)).toThrow('outside'))
  it('accepts exact freshness boundaries', () => { expect(() => validateFreshness(700, 1000, 300)).not.toThrow(); expect(() => validateFreshness(1300, 1000, 300)).not.toThrow() })
  it('rejects invalid verifier clocks', () => expect(() => validateFreshness(100, -1)).toThrow('clock'))
  it('rejects invalid tolerance', () => expect(() => validateFreshness(100, 100, -1)).toThrow('tolerance'))
  it('accepts the signed event exactly once', () => { const store = new InMemoryWebhookAdmissionStore(); const result = admitIncomingWebhook(signed(), store, 1000); expect(result.outcome).toBe('accepted'); expect(store.size()).toBe(1) })
  it('returns replay for the same tenant event and body', () => { const store = new InMemoryWebhookAdmissionStore(); const input = signed(); admitIncomingWebhook(input, store, 1000); const replay = admitIncomingWebhook(input, store, 1000); expect(replay.outcome).toBe('replay') })
  it('returns conflict for the same event with changed body', () => { const store = new InMemoryWebhookAdmissionStore(); const input = signed(); admitIncomingWebhook(input, store, 1000); const changed = { ...input, rawBody: '{"amount":11}', signature: '' }; changed.signature = signIncomingWebhook(changed, changed.secret); expect(admitIncomingWebhook(changed, store, 1000).outcome).toBe('conflict') })
  it('isolates same event ids by tenant', () => { const store = new InMemoryWebhookAdmissionStore(); const input = signed(); admitIncomingWebhook(input, store, 1000); const other = { ...input, tenantId: 'tenant-b', signature: '' }; other.signature = signIncomingWebhook(other, other.secret); expect(admitIncomingWebhook(other, store, 1000).outcome).toBe('accepted') })
  it('isolates same tenant events by event id', () => { const store = new InMemoryWebhookAdmissionStore(); const input = signed(); admitIncomingWebhook(input, store, 1000); const other = { ...input, eventId: 'evt-2', signature: '' }; other.signature = signIncomingWebhook(other, other.secret); expect(admitIncomingWebhook(other, store, 1000).outcome).toBe('accepted') })
  it('stores the fingerprint rather than raw body', () => { const store = new InMemoryWebhookAdmissionStore(); const input = signed(); const result = admitIncomingWebhook(input, store, 1000); expect(result.record?.fingerprint).toBe(bodyFingerprint(input.rawBody)); expect(JSON.stringify(result.record)).not.toContain(input.rawBody as string) })
  it('returns the original status and body on replay', () => { const store = new InMemoryWebhookAdmissionStore(); const input = signed(); store.claim(input, 201, { applied: true }); const replay = store.claim(input, 500, { applied: false }); expect(replay.record?.statusCode).toBe(201); expect(replay.record?.responseBody).toEqual({ applied: true }) })
  it('completes a claimed event with the final outcome', () => { const store = new InMemoryWebhookAdmissionStore(); const input = signed(); store.claim(input); const record = store.complete(input.tenantId, input.eventId, input.rawBody, 200, { ok: true }); expect(record.responseBody).toEqual({ ok: true }); expect(store.get(input.tenantId, input.eventId)?.statusCode).toBe(200) })
  it('rejects completion for a changed body', () => { const store = new InMemoryWebhookAdmissionStore(); const input = signed(); store.claim(input); expect(() => store.complete(input.tenantId, input.eventId, '{"changed":true}', 200, {})).toThrow('match') })
  it('deletes an event for explicit recovery', () => { const store = new InMemoryWebhookAdmissionStore(); const input = signed(); store.claim(input); expect(store.delete(input.tenantId, input.eventId)).toBe(true); expect(store.get(input.tenantId, input.eventId)).toBeUndefined() })
  it('expires records through the injected clock', () => { let now = 0; const store = new InMemoryWebhookAdmissionStore(() => now, 100); const input = signed(); store.claim(input); now = 100; expect(store.size()).toBe(0); expect(store.claim(input).outcome).toBe('accepted') })
  it('copies records on reads', () => { const store = new InMemoryWebhookAdmissionStore(); const input = signed(); const result = store.claim(input); result.record!.tenantId = 'mutated'; expect(store.get(input.tenantId, input.eventId)?.tenantId).toBe('tenant-a') })
  it('clears all records for test/recovery lifecycle', () => { const store = new InMemoryWebhookAdmissionStore(); const input = signed(); store.claim(input); store.clear(); expect(store.size()).toBe(0) })
  it('uses a deterministic signing material layout', () => { const input = base(); expect(signingMaterial(input).toString('utf8')).toBe('v1:tenant-a:evt-1:1000:{"amount":10}') })
  it('rejects clock-skew before claiming state', () => { const store = new InMemoryWebhookAdmissionStore(); expect(() => admitIncomingWebhook(signed(), store, 2000)).toThrow('outside'); expect(store.size()).toBe(0) })
  it('rejects invalid signatures before claiming state', () => { const store = new InMemoryWebhookAdmissionStore(); expect(() => admitIncomingWebhook({ ...signed(), signature: '00' }, store, 1000)).toThrow('invalid'); expect(store.size()).toBe(0) })
  it('does not leak secrets in admission errors', () => { try { verifyIncomingSignature({ ...base(), signature: 'bad' }) } catch (error) { expect((error as Error).message).not.toContain('secret-a') } })
  it('keeps status codes typed for client handling', () => { try { validateFreshness(0, 10) } catch (error) { expect((error as WebhookAdmissionError).statusCode).toBe(400) } })
})
